### ISSUE TITLE
Feature under development: Sting transition

### ISSUE THREAD

**Issue by Julusian** [CasparCG/server#1008]
CasparCG supports some basic transitions between producers on a layer. The range of options is rather limited and doing anything more complex requires running them manually in seperate layers and using mask layers which quickly gets complicated. 
This could be made a lot cleaner by extending the transition producer with a sting style. This would utilise a couple of FFmpeg Producers to generate the mask to apply to the old producer and an overlay layer.
Doing this would also allow the user to make their own wipe/reveal patterns as well as sting transitions.

Key features:
* Define a video clip to use as the mask doing the transition from foreground- to background clip. The mask clip will be luma-keyed and white fill to paint out the region for the upcoming clip to show.
* Optionally define a video clip with alpha to play as the sting-wiper overlay keyed on top of the transition.
* The duration of the transition should be taken as the duration of the mask file
* Specify the trigger point (the point during the transition to start the destination producer)

The motivation behind this to provide the sting transition similar to that on an ATEM, using a wipe between the producers, but with a soft edge (or any kind of shape).

**Comment by PeterAkakpo** [comment]
@Julusian what is a sting transition, how does the visual look like

**Comment by premultiply** [comment]
A stinger transition is an keyed animation which runs during/over a classic transition between two sources/clips. This can be seen often in sport events when switching from live camera to slowmotion replay and back to live again.

**Comment by jesperstarkar** [comment]
This feature consists of two parts:
1) The mask transition: Instead of just mixing, wiping, sliding between two clips, you can now use a video file to mask the transition. Create the mask clip however you'd like. Black pixels show the current playing clip, white pixels show the next playing clip and values between do alpha blending. This way you can "paint" out the old clip with the new however you'd like. The new clip is playing in the background, and plays as it gets "painted in".

2) The wipe overlay: At the same time as this happens, a fourth clip can play at a new top layer, as decor covering up the ongoing transition. This is behaves like @premultiply describes.
