### ISSUE TITLE
Flash: Review and Merge pending pull requests on templatehost for inclusion in 2.2.0

### ISSUE THREAD

**Issue by silid** [CasparCG/server#1074]
templatehost has a number of outstanding pull requests that should be considered for release in 2.2.0

https://github.com/CasparCG/templatehost/pulls

**Comment by dotarmin** [comment]
@silid I we discussed earlier, those PR's can be included in a v2.2 release as long as somebody verify that they work as expected and mark each PR as LGTM or something.

Best regards,
/Armin

**Comment by dotarmin** [comment]
I will close this issue because PR's are in the [TemplateHost (https://github.com/CasparCG/templatehost/pulls) repository. 

However, I can make sure they are merged into Server v2.2 when PRs are merged and built. 
@jeansson will probably be the one that will check the PRs and build new TemplateHost files.

Best regards,
Armin
