### ISSUE TITLE
Template host for HTML templates

### ISSUE THREAD

**Issue by dotarmin** [CasparCG/server#1084]
### Description
Instead of initialising multiple CEFs created when playing HTML templates, the server would benefit performance-wise of having one CEF with a template host per video-layer in the same way as we have for Flash today. This would also require support for the `cg_layer` as in the flash template host.

`CG [video_channel:int]{-[layer:int]|-9999} ADD [cg_layer:int] [template:string] ...`

### Solution suggestion
Load a template host for CEF (transparent template?) with a predefined protocol for how templates communicate within the template host.

Best regards,
Armin

_(Originally authored by Andreas Andersson)_ :)

**Comment by premultiply** [comment]
I do not like the sublayer concept with the layer-internal depencies and the special AMCP CG commands at all.
I prefer dropping it completly and switch to unified basic AMCP command headers for playout of anything on any layer if possible.

**Comment by jesperstarkar** [comment]
I second that @premultiply. I see this as a use case to be solved by the template itself rather than a native concept in AMCP. You are free to invoke methods and pass data to a CEF layer, so I don't see how a native concept - that can add complexity - would be better than just utilising the tools that are already at hand.
