### ISSUE TITLE
OSC POSITION NOT UPDATED AFTER SEEK

### ISSUE THREAD

**Issue by PeterAkakpo** [CasparCG/server#1271]
### Expected behaviour
after a CALL SEEK has been issued , osc "../foreground/file/time" should also be updated to reflect the not position.

### Current behaviour
the OSC "../foreground/file/time" does  not reflect the correct position.
----

### Steps to reproduce
1.  play a file, PLAY 1-0 CLIP
2. CALL 1-0 SEEK 5000
3. Monitor the "../foreground/file/time" values in your application or 
4. Type DIAG and check the FFMPEG time counters

### Environment
* Commit: latest build
* Server version: 2.3
* Operating system: Windows 10

---

### Screenshots
If applicable, add screenshots as complementary information.

**Comment by vimlesh1975** [comment]
I tried this to reproduce with version dated 30.03.2020 but In my system it is working as desired.

**Comment by Julusian** [comment]
@PeterAkakpo It appears to be working fine for me when looking at diag. Could you retest to confirm?

Behaviour could have changed with https://github.com/CasparCG/server/commit/a1367bf137615576bd8e2d2a05ff3525bd87ed6a but that was a month before you opened this and it shouldnt have changed since then

**Comment by PeterAkakpo** [comment]
it's working now
