### ISSUE TITLE
Server crash on zero route delay

### ISSUE THREAD

**Issue by ducthiem90** [CasparCG/server#1295]
I tested new route producer (zero route delay). It's good. But there was a user error that caused the server to crash:
PLAY 1-2 ROUTE://1-1
PLAY 1-1 ROUTE://1-2

I think we should handle this bug to avoid the problem by mistake

**Comment by dotarmin** [comment]
@Julusian is this related to the fix #1267?

**Comment by ducthiem90** [comment]
> @ducthiem90 thanks for reporting. Can you provide us with more information such as commit and version you are using?
> 
> @Julusian is this related to the fix #1267?

It's new build version: casparcg-server-94db7f222d852947eb61ae10b3ac6c9cbbd785be-windows.zip
or any build after 2020-04-28

**Comment by dotarmin** [comment]
Can you reproduce this issue in the v2.3.0 LTS Beta 1 release? 
Are you able to include a dump file if it happens or some additional information?

@jesperstarkar and @scriptorian, related to merge of #1267?

**Comment by jesperstarkar** [comment]
@dotarmin this is not to be considered a bug, at least not a regression, more of a missing feature. @ducthiem90 describes an "illegal" operation/deliberate user error in the original post.

A suggestion would be to add some safe guarding.

**Comment by dotarmin** [comment]
> this is not to be considered a bug, at least not a regression, more of a missing feature.

Agree, just not sure if it's a missing feature or if it should have been a part of #1267 :)

> A suggestion would be to add some safe guarding.

Indeed, some sort of safe guard is needed. If we can eliminate those kind of errors it would be a win-win situation for our users and for the software it-self.

**Comment by dimitry-ishenko** [comment]
IMHO this should be safeguarded against as @jesperstarkar has suggested. I have a slightly different problem along the same lines: the server crashes when trying to create a thumbnail of a corrupt file.

@dotarmin maybe a separate bug should be created to try to make the server crash-proof against certain SNAFUs?

**Comment by Julusian** [comment]
I would argue that this is a regression introduced by #1267. It wasn't a problem before then, and while it may be unlikely to be hit it will be by some. And as it is a crash (rather than something going black/freezing on a frame), I think this is severe and should be fixed asap.

@dimitry-ishenko crashes while creating a thumbnail? But that job is outsourced to the scanner now to avoid situations like this. Either way, that should be a separate report as it will be a different fix

**Comment by jesperstarkar** [comment]
Thanks @Julusian

**Comment by dimitry-ishenko** [comment]
> But that job is outsourced to the scanner now to avoid situations like this.

@Julusian that's for an older version, which is why I haven't reported it. I was just trying to bring up a general idea that the server should be fault-tolerant as much as possible.

**Comment by Julusian** [comment]
@dimitry-ishenko ah ok, that makes sense. In general it does try to catch and swallow and log as many errors as possible (sometimes too agressively eg https://github.com/CasparCG/server/issues/1296), but some are fatal even if it doesn't sound like they should be and just need a simple if guard to protect against instead

**Comment by jesperstarkar** [comment]
@Julusian how would you guard against 1-1 to 1-2, 1-2 to 1-3 and 1-3 to 1-1?

**Comment by LRTNZ** [comment]
> @Julusian how would you guard against 1-1 to 1-2, 1-2 to 1-3 and 1-3 to 1-1?

Hmmm, maybe what could be done, is to create an ordered list of the steps in a route producer.  
What I mean by this, is the producer will take the list of `route producer steps` from its source (if it exists, otherwise initialise with the initial value of the source for the new producer), and append it's destination to it.  
Then a producer gets made with a source of the destination of that first producer, so it takes the 'source 1, destination 1' list and makes it 'source 1, destination 1, destination 2', and so on. When a new route producer goes to be made from a source, the destination chosen would be compared to the list of 'route producer steps' in the source for the new route, to ensure that it will not loop back onto itself.

**Comment by RuneFog** [comment]
> > @Julusian how would you guard against 1-1 to 1-2, 1-2 to 1-3 and 1-3 to 1-1?
> 
> Hmmm, maybe what could be done, is to create an ordered list of the steps in a route producer.
> What I mean by this, is the producer will take the list of `route producer steps` from its source (if it exists, otherwise initialise with the initial value of the source for the new producer), and append it's destination to it.
> Then a producer gets made with a source of the destination of that first producer, so it takes the 'source 1, destination 1' list and makes it 'source 1, destination 1, destination 2', and so on. When a new route producer goes to be made from a source, the destination chosen would be compared to the list of 'route producer steps' in the source for the new route, to ensure that it will not loop back onto itself.

Sounds like maintaining a directed graph of the routing would be a solution. When adding a route, add the edge in the graph and check for cycles.

**Comment by jesperstarkar** [comment]
Patched and handled in https://github.com/CasparCG/server/pull/1306

**Comment by Julusian** [comment]
There is still a delayed crash after entering this state. I dont know if that is something we should try to handle under this issue
cc @dotarmin

**Comment by dotarmin** [comment]
@Julusian, I think we should try to have it fixed in this version and try to find the core reason why it's happening. However, we have to other issues to solve for v2.3.0 LTS milestone and should maybe focus on those first, what do you think @Julusian ?

**Comment by Julusian** [comment]
The remaining issue of a delayed crash has its own task https://github.com/CasparCG/server/issues/1314
