### ISSUE TITLE
VP9 video reproduction

### ISSUE THREAD

**Issue by brucedk** [CasparCG/server#1318]
### Description
capacity of VP9 video reproduction. A use is to have a video with transparency with much less size than prores 4444 or other codecs, and has no need to create 2 files (one to rgb and another to alpha)

### Solution suggestion
build ffmpeg with libvpn maybe? but I think it already has....

**Comment by hreinnbeck** [comment]
I've been using VP8 and 9 with alpha in the HTML producer for years.  Offers a lot more control (which you usually want if you need alpha).  Otherwise I think CCG should play VP8/9 if you change the file ending to e.g. mp4 (webm and more are not on the list of file extensions in CCG [which I actually want to move into the config]).

**Comment by brucedk** [comment]
Ok, made a test here, if the ending is mp4 it really works, but the best is if it works as webm or mkv... but thanks anyway

**Comment by Julusian** [comment]
@hreinnbeck yeah I really dont like how we have to whitelist file extensions. And even less that ffmpeg also blacklists extensions for other producers..

But short term, let just add some more to the list https://github.com/CasparCG/server/blob/master/src/modules/ffmpeg/producer/ffmpeg_producer.cpp#L213.
Could someone let me know what wants to be added and I can do that

**Comment by dimitry-ishenko** [comment]
`.m2ts` and `.nut`

**Comment by walterav1984** [comment]
`.flac .opus .ogg .ogv .oga`

**Comment by brucedk** [comment]
`.webm` and `.webp`

**Comment by Julusian** [comment]
Those have been added in b8f2206d953c42ed6f62afdbbddf2f91ad991fd7 (2.3-lts branch)
