### ISSUE TITLE
Datapath cards in producer and consumer

### ISSUE THREAD

**Issue by nyok92** [CasparCG/server#1373]
### Description
It would be great to have datapath/ vision capture cards available for producer and consumer in Casparcg server like blackmagic or bluefish.
Maybe there already is some kind of solution somwhere but didn't found it, and moreover i'm not Cpp developper.

### Solution suggestion
there is an sdk for development : 
[]https://www.datapath.co.uk/datapath-current-downloads/vision-capture-card-downloads/vision-sdks
and maybe with use of :
[]https://github.com/mufunyo/OBS-DatapathPlugin

Thnaks for any help ! :)

**Comment by didikunz** [comment]
Can you explain, what is better / different with these cards?

**Comment by nyok92** [comment]
It is neither different nor better. It's just that i've got plenty of theese cards. :) Would it be good to support this brand if possible.

**Comment by didikunz** [comment]
The problem is, that it is a big undertake to support a type of video card. And these are only for SDI input, in a Video Wall setup, if I understand their website right. So I think it would not be a thing that would be for the benefit of most of our users. But if you need it, you can hire a c++ developer and fork CasparCG...

**Comment by Julusian** [comment]
We will consider a pull request supporting this, but I don't think it worth keeping this issue open
