### ISSUE TITLE
DISPLAY is not set

### ISSUE THREAD

**Issue by dequedrapha** [CasparCG/server#1445]
### Expected behaviour
Normal startup of the Server

### Current behaviour
Throwing the error: `Failed to open X11 display: make sure the DISPLAY environment variable is set correctly `

----

### Environment
* Server version:  v2.2
* Operating system: Ubuntu 20.04 (VPS)

---

Hey there!

Ive tried to install casparcg on Debian 11 previously but that didnt went well... so i try it now on Ubuntu. Ive followed the steps in the Building.md and successfully created the docker image, build directory and staging dir. But every startup throw the same error. Some ideas how to fix it? Or did i overread something? I would be really happy about some replies :>

Rapha.

**Comment by Bohoaush** [comment]
Hi, 

it looks like x-server is not running or you are not using it to start CasparCG.
This could be because you are using Ubuntu Server or maybe you are trying to run CasparCG over ssh.
If you are on Ubuntu Server you can try installing x11.
If you have desktop Ubuntu version, try running CasparCG from GUI, or it might be possible (although I didn't personally try it) to start it over ssh session initialized with -X parameter.
Let me know if neither of this is the case.

Another thing to consider is that many VPSs won't meet CasparCG's hardware requirements, so it won't run, or could have performance issues.

**Comment by dequedrapha** [comment]
Hey thanks for your answere!

So now ive installed Ubuntu Desktop and it seems to work fine (except the connection between the server and the media-server). But my goal is to run it like 24/7 to create a scheduled livestream. Is that possible without having an remote Desktop connection the hole time open? 

To my vps components:

I have currently a testing Environment with 2vcores and 6gb RAM. After the Server runs i will move to 4vcores and 12gb RAM.

**Comment by Bohoaush** [comment]
Hi, 
try using x11vnc instead of rdp. x11vnc shares existing graphical sessions, unlike vncserver or some rdp servers which create new ones, so it won't close the graphical session when you close the vnc connection.

**Comment by dequedrapha** [comment]
Okay ive tested it out and it works! 
But somehow i have some problems with the Media Server now. But nothing for this issue ig...

Thank you for your help! :D
