### ISSUE TITLE
Problem playing files with extra dots in the filename when omitting the extension

### ISSUE THREAD

**Issue by ianshade** [CasparCG/server#1495]
### Expected behaviour
File called `file.something.mov` (having what appears like a double extension, but technically it can be a dot and anything that has a meaning to the creator of the file, and can include spaces) can be played with `PLAY 1-1 file.something` (omitting the actual extension), similarly to how `file.mov` can be played with `PLAY 1-1 file`

### Current behaviour
`#404 PLAY FAILED`

----

### Steps to reproduce
1. Start CasparCG
2. Make a media file with two "extensions", for example `file.2.mov` or `file.mp4.mov`, or `file.copy.mov`, or even `file.a b c.mov`
3. Try playing the file, e.g. `PLAY 1-1 file.2`

### Environment
* Commit: https://github.com/CasparCG/server/commit/b0ecbeea48e9a9548199ed1d2cf0d241fa3695fa
* Server version: v2.4
* Operating system: Windows 11

---

This appears to be a bug introduced here https://github.com/CasparCG/server/commit/bb0499184dce4fde44427ec93c5e1c59cf9af56c#diff-4dc9fe842cb72ce9c48e6caaa8245a20cf661bbe2110a45ecc8c125d3cde32d4R323-R326

**Comment by Julusian** [comment]
I have a feeling I made this change thinking that if a file extension is specified then we should strictly match, so that a `play 1-1 file.mp4` doesnt try searching for a `file.mp4.mp4` or similar.
But I did not think of the consequence of filenames containing `.` would no longer work.

I guess the fix is to remove that search stop, and let it try and find `file.mp4.mp4` before giving up.
