### ISSUE TITLE
Native AMCP over RS232/RS422 Serial Interface

### ISSUE THREAD

**Issue by premultiply** [CasparCG/server#171]
Server process should open a configurable serial port like the TCP socket for AMCP protocol.

http://casparcg.com/forum/viewtopic.php?t=1704

**Comment by yapus** [comment]
From a perspective of redundancy and constant reaction time serial interface thread on the same machine as CasparCG server is essential. This is because TCP stack in Windows7 can show "miracles" form time to time, especially when you have lot's of network interfaces from different subnets and want to play media from a shared network drive.

We're going with @HellGore 's number 2 - implement it directly in the CasparCG server.
For the constant reaction time - separate high-priority thread inside CasparCG process. 
For the redundancy - we plan to use two (or three - for the quorum rule) serial interfaces receiving almost synchronous sets of commands.

**Comment by yapus** [comment]
#358 pull request contains some work on adding "serial" controller with PBUS protocol. I suggest there should be protocol "pbus" in controllers.serial, rather than making PBUS one and only default serial controller.
