### ISSUE TITLE
1080p50 outputs as 1080i50 without key.

### ISSUE THREAD

**Issue by coral** [CasparCG/server#305]
Hello!

I have now tested 1080p50 output with Decklink 3D Extreme and Decklink 4K Extreme and both have the same problem.

1080p5994 outputs as 1080i5994.

They do not output key/fill in 1080p modes, only 1080i50 but then without key.
This seems to be a bug in CasparCG.

Tested both 2.0.6 and latest build.

```
[2014-09-11 14:50:12.383] [054F4338] [info]    video_channel[1|1080p5994] Successfully Initialized.
[2014-09-11 14:50:12.384] [056D1D90] [info]    DeckLink 4K Extreme [1-1|1080p5994] Using custom allocator.
[2014-09-11 14:50:12.385] [056D1D90] [info]    DeckLink 4K Extreme [1-1|1080p5994] Disabled low-latency mode.
[2014-09-11 14:50:12.385] [056D1D90] [info]    DeckLink 4K Extreme [1-1|1080p5994] Enabled external keyer.
[2014-09-11 14:50:12.396] [056D1D90] [info]    DeckLink 4K Extreme [1-1|1080p5994] Reference signal: not detected.
[2014-09-11 14:50:12.428] [054F4338] [info]    DeckLink 4K Extreme [1-1|1080p5994] Successfully Initialized.
[2014-09-11 14:50:12.435] [055E06B0] [info]    output[1] DeckLink 4K Extreme [1-1|1080p5994] Added.
```

![108059](https://cloud.githubusercontent.com/assets/2163363/4234077/42b07d26-39b3-11e4-9111-2230e70ec7ad.jpg)
![108050](https://cloud.githubusercontent.com/assets/2163363/4234079/45e9cbb4-39b3-11e4-9de4-d07807e50c13.jpg)

**Comment by TracyPeterson** [comment]
Can we look into this again?  A Decklink 4k can certainly do more than 1080i and over single link.  The new quad 2's can do 1080p with key four times.  But not in Caspar.

**Comment by HellGore** [comment]
What do you mean with not in Caspar? It is a limitation in Decklink 4K Extreme. Quad 2 is a much newer card. In what program can Decklink 4K Extreme output separate key in 1080p?

**Comment by TracyPeterson** [comment]
I'll confirm with Blackmagic by phone, but I'm certain the keyer operates
at all resolutions supported.  Though, wouldn't be too unusual for them to
not operate.

**Comment by jesperstarkar** [comment]
This just in: https://twitter.com/blackmagic_news/status/733476605339656192

**Comment by TracyPeterson** [comment]
How timely!

**Comment by HellGore** [comment]
I can confirm that 10.6.6 does *not* add external keying in 1080p to Decklink 4K Extreme. I can't speak for the Decklink 4K Extreme 12G though. Furthermore I'm guessing the release notes regarding Decklink 4K SDI is about internal keying since it does not have dual BNC outputs only one in and one out.

**Comment by TracyPeterson** [comment]
I'll call on blackmagic then and ask them why the conflicting information.  I'm going to be in San Mateo today anyway.






On Fri, May 20, 2016 at 2:33 AM -0700, "HellGore" <notifications@github.com> wrote:












I can confirm that 10.6.6 does not add external keying in 1080p to Decklink 4K Extreme. I can't speak for the Decklink 4K Extreme 12G though. Furthermore I'm guessing the release notes regarding Decklink 4K SDI is about internal keying since it does not have dual BNC outputs only one in and one out.

**Comment by HellGore** [comment]
They didn't mention Decklink 4K Extreme in the release notes, just Decklink 4K SDI. Si I guess there is no conflicting information. Did I miss something?

**Comment by TracyPeterson** [comment]
No, I read the note and thought that since 4K extreme is bigger card with more features it would support that.  I still want to know I'll let you know if I find out.






On Fri, May 20, 2016 at 6:49 AM -0700, "HellGore" <notifications@github.com> wrote:












They didn't mention Decklink 4K Extreme in the release notes, just Decklink 4K SDI. Si I guess there is no conflicting information. Did I miss something?

**Comment by HellGore** [comment]
This could work in driver 10.8.2. I have not tested though.
