### ISSUE TITLE
Feature Request: AMCP Command for OSC Port

### ISSUE THREAD

**Issue by oneofsomany** [CasparCG/server#307]
Can we have an AMCP command to request an OSC port number from CasparCG so we can then have multiple clients on the same system, bound on their own unique port without need of modifying the config.

For Example..
OSC LIST .. could list all currently used OSC ports for diagnostic purposes
OSC REQUEST .. would return a unique and unbound port number on the local server which the client can use. This would not work for remote clients. you could check the IP address when the REQUEST command is used to determine if the server should error and inform the client that they are remote.
OSC REQUEST <port> .. could be used by remote clients to tell caspar which port they are using

**Comment by dimitry-ishenko** [comment]
:+1:

**Comment by HellGore** [comment]
Actually I have now started thinking about maybe it would be better to do like the Behringer X32 and only send OSC to "clients" that have themselves started OSC conversations with the "server". We would then in the CasparCG Server have an OSC listener as well. If a client sends a `/ping` OSC message to the CasparCG Server that client will be on the subscription list for the next 70 or something seconds.

`/ping` and 70 seconds time out is good because Olle has pointed out that TouchOSC has a built in feature for this, and it is hardcoded to `/ping` and 60 seconds intervals.

The nice thing about this is also that the UDP port that the CasparCG Server will respond on will be the same as it got the `/ping` on. This way there would be no more need for configuring a port for the CasparCG Server to send to, only to listen on.

**Comment by dimitry-ishenko** [comment]
:+1:  :+1:

**Comment by Julusian** [comment]
In 2.4 it is possible to send `OSC SUBSCRIBE 12345` to receive OSC data on the specified port number, and  `OSC UNSUBSCRIBE 12345` to stop receiving data.
The subscription will live as long as the AMCP connection is left open.

I feel like a future release should change the default behaviour to not send by default to connected clients, but I have no immediate plans to change that as it will upset a lot of client sotware
