### ISSUE TITLE
Incorrect Interlaced YUV Rendering

### ISSUE THREAD

**Issue by ronag** [CasparCG/Server#328]
CasparCG currently vertically scales interlaced CbCr channels in YUV420 formats. Which is incorrect and causes data between different fields to be mixed together. Should probably implement field separate interlace aware scaling on the gpu. Or as a workaround force interlaced YUV420 to YUV422 using ffmpeg before sending to the mixer.

**Comment by NandaKr** [comment]
Wrong color gamut will be a big turn down for all casparcg fans. 
Just a though:
    Can openCV be used to compare a standard color bar signal with casparcg signal (same color bar with gamut error) to calculate how much correction should be applied to the mixer? If this works we can programmatically correct the error till a 10 bit fix comes up.

**Comment by ronag** [comment]
@seccpur: Please create a new issue for the unrelated problem you are describing.

**Comment by walterav1984** [comment]
Duplicate ticket?
https://github.com/CasparCG/Server/issues/41
http://casparcg.com/forum/viewtopic.php?f=3&t=1631

Workaround:
Preconvert your 4:2:0 interlaced DV/Mpeg2/H264 footage in ffmpeg with the following parameter "-vf scale=interl=1" and choose a output videocodec that has 4:2:2 or higher chroma subsampling support for instance "prores" or raw "uyvy422". Two examples below:

"ffmpeg -i chromaerror.dv -vf scale=interl=1 -c:v prores chromafix422i.mov"
"ffmpeg -i chromaerror.dv -vf scale=interl=1 -vcodec rawvideo -pix_fmt uyvy422 -acodec copy -f avi chromafix422i.avi"

Native CasparCG Solution:
Since CasparCG ffmpeg producer can use ffmpeg parameters and or filters its possible to fix this in realtime with no hacks in CasparCG source code! Only tested file playback, streams IP/DV have not been tested yet! The following AMCP FILTER command fixes the chroma upsampling error:

play 1-1 chromaerrorfootage FILTER scale=interl=1,format=pix_fmts=uyvy422

Please update the CasparCG wiki "Chroma Subsampling" and "Producer > Filter" pages with these Workaround/Fixes for interlaced Chroma 4:2:0 based footage:

http://casparcg.com/wiki/Content_/_Media#Chroma_Subsampling
casparcg.com/wiki/CasparCG_Server#Producers_.28Input_Modules.29

Except from being GPU accelerated, and this FILTER preset can be added as a template to the CasparCG Client could this bug be closed?

**Comment by ronag** [comment]
Fixed with new ffmpeg producer
