### ISSUE TITLE
HTML Producer doesn't support 3d transforms.

### ISSUE THREAD

**Issue by philetaylor1** [CasparCG/Server#331]
The CSS properties backface-visibility: none; and transform-style: preserve-3d; have no effect on HTML templates with CasparCG 2.0.7 server. 

I have verified this with my own templates and a test website http://thewebrocks.com/demos/3D-css-tester/ which works fine on cefclient.exe (using same libcef.dll version as CasparCG)

**Comment by coral** [comment]
It seems that the CEF version compiled with Caspar is compiled without hardware acceleration so a lot of stuff (3D transformations) doesn't work.

**Comment by ronag** [comment]
Hardware acceleration is enabled. WebGL works fine. I think it has more to do with the underlying chromium version.

**Comment by philetaylor1** [comment]
From my research, It seems that the released version of CEF3 doesn't support 3d transforms when operating in offscreen rendering mode. This is fixed in newer builds of CEF3. As the API seems to have changed quite a bit, it doesn't look like a trivial fix though.

**Comment by ronag** [comment]
Yea, the whole Blink transition. They even disabled offscreen rendering for some version in between.

**Comment by itodorovic** [comment]
After asking in forum, to repeat it here: Can something be done to compile newer CEF3 into Server 2.1? There are many claims 3D CSS transformations are working now, and users really need them.
Thanks.

**Comment by HellGore** [comment]
@itodorovic  It is not something we are looking into right now, but probably in the future after 2.1 has been released.

**Comment by jesperstarkar** [comment]
Hmm, upgrading CEF to support GPU/3D-transform + getting a newer CEF with font smoothing support should, in my opinion, be a top priority as this is needed to have HTML templates work properly.

Have you monitored the CEF threads on this topic? I don't get the whole picture, as I don't understand the code, but it seems something has changed when it comes to Win10 on this topic.

**Comment by itodorovic** [comment]
It's hard to get the whole picture. 

CEF people claim they've resolved this in release: [January 27, 2015: Version 3.2171.1979](https://bitbucket.org/chromiumembedded/cef/wiki/ReleaseNotes)
> Re-implement off-screen rendering using the new delegated rendering approach (issue #1257). This implementation supports both GPU compositing and software compositing (used when GPU is not supported or when passing --disable-gpu --disable-gpu-compositing command-line flags). GPU-accelerated features (WebGL and 3D CSS) that did not work with the previous off-screen rendering implementation do work with this implementation when GPU 
 
but some Caspar server builds that tried to incorporate this fail on Win 7 here, don't know about Win 10. When I say these builds fail: they render both WebGL and CSS in 3D, but frame rate is a disaster and there is a ton off errors in the console. Regular 2.0.7 and 2.1 server builds render WebGL correctly and with good frame rate, but don't render CSS transforations at all. 

Thanks for pointing out how important this is, because these are features you can not do at all with Flash templates, and can attract many people to Caspar if they should work as they are supposed to. Modern broadcast graphics demand some real 3D features, you can not fake 3D in 2D forever. Problem is that WebGL vs CSS toolchains are completely different, and I'm just now struggling to re-implement something in WebGL which is working just fine with CSS in browser, but CSS fails in Caspar. It could easily happen that just in time I'm finished this, CSS transformations will start working in Caspar and all work will go in wain. It should be great if our tool-chains would not depend on correct Caspar build.

If developers need any testing on Win 7 and Linux please ask, I'm more then willing to help with this.

**Comment by jesperstarkar** [comment]
This is not just about 3D support as you point out. Most important is font smoothing at the moment, as the SVG-font workaround is terrible. Then 3D transforms, then 3D/WebGL.  We should at least have an updated CEF version to get font smoothing, even if this implementation doesn't give GPU/3D support.

**Comment by ronag** [comment]
Will be resolved by https://github.com/CasparCG/Server/pull/611
