### ISSUE TITLE
No font aliasing on HTML producer

### ISSUE THREAD

**Issue by coral** [CasparCG/server#337]
Wrote some new templates using canvas for a new project. Getting terrible font performance, any thoughts?

**CasparCG**
![Caspar](http://i.imgur.com/82Yor9t.jpg)

**Chrome Embedded**
![Caspar](http://i.imgur.com/f4KchvB.jpg)

Is the official server compiled with some other font rendering library?
Cleartype etc is turned off.

**Comment by hummelstrand** [comment]
Turn on ClearType to get anti-aliased text with the HTML producer. Turn it
off to avoid problems with Flash and alpha. It's an either or, I think...

**Comment by coral** [comment]
Tried, didn't change anything. Seems to be an issue with the <canvas> font rendering pipeline. Will try HTML font rendering.

**Comment by coral** [comment]
HTML font rendering looks better but not perfect, def seems to be issue with the canvas rendering pipeline & CasparCG.

**Comment by elanvrt** [comment]
Neither Flash nor HTML were ever intended for broadcast-quality CG machines, rather for web-style graphics that also must run on low-end devices. That's why CG OEM's use proprietary font render engines.

What you can try is turning on x2  or x4 FSAA (full screen antialiasing), a feature of the better GPU cards.
That works by internally rendering the text in a higher resolution than the screen, then scaling it down by hardware. Use the control panel that came with your GPU card, its not a Windows setting. Turning on FSAA may affect performance.

**Comment by ronag** [comment]
Honestly, I don't think any proprietary font render can beat the Flash font renderer.

**Comment by ronag** [comment]
The problem here is probably related to Chrome, and specifically the version which CasparCG uses.

**Comment by coral** [comment]
LOL @elanvrt . This has nothing to do with "proprietary font renders" etc + the notion of "broadcast-quality CG machines" is just software wrapped in a nice box, often based on existing Windows technologies. The graphic and rendering looks fantastic on Chrome but not, as @ronag says, the version that CasparCG currently builds with.

**Comment by Julusian** [comment]
@dotarmin I believe this is fixed with the updated html producer

**Comment by dotarmin** [comment]
@Julusian I think so aswell but I think we should verify it just in case 😄

**Comment by jesperstarkar** [comment]
It doesn't work out of the box. I'll investigate.

**Comment by ronag** [comment]
@jesperstarkar is this fixed in 2.2?
