### ISSUE TITLE
HTML producer tracing "Requested animation frame" every rame.

### ISSUE THREAD

**Issue by jesperstarkar** [CasparCG/Server#344]
Do we want logging of every "Requested animation frame" with log-level Trace??

Line 276-277 of html_producer.cpp:

CASPAR_LOG(trace)
<< print() << L" Requested animation frame";

**Comment by HellGore** [comment]
I dont think it is a problem really, trace is the most verbose log level

**Comment by jesperstarkar** [comment]
But for what purpose? Trace is comonly used during development of templates and clients. What good does it do to have a trace pr frame cloaking the log?

Mvh. Jesper

Jesper Stærkær
Stærkær AS
Mob.: 454 26 094

**Comment by HellGore** [comment]
Trace logging is usually left as is in shipped products, in order to be able to later enable trace logging without having to recompile the entire server and readding the logging statement.

If log level trace has been enabled then it is expected that logging statements may be very verbose and frequent.
