### ISSUE TITLE
PLAY after failed LOAD

### ISSUE THREAD

**Issue by ronag** [CasparCG/Server#385]
Doing a PLAY after a failed LOAD gives a bit of an ambiguous behaviour. PLAY shouldn't actually do anything after a failed LOAD but that does not seem to be the case.

**Comment by HellGore** [comment]
Could you elaborate on the behaviour you are seeing?

As far as I can see stage::load() is not event called if the frame_producer construction throws, since the producer is passed as a parameter to stage::load().

Also is this in 2.0.7 or in 2.1.0?

**Comment by ronag** [comment]
Tried it in 2.0.7. but it probably in both. You can easily reproduce it.

```
LOAD 1 existingclip
PLAY 1
LOAD 1 nonexistingclip
PLAY 1
```

**Comment by HellGore** [comment]
Do you mean that the `LOAD 1 nonexistingclip` should abort the playing of `existingClip` since the file was not found? instead of just return a `404 LOAD FAILED` and continue with `existingClip` (the behaviour I'm seeing in both 2.0.7 and 2.1.0)? For me `LOAD 1 nonexistingclip` followed by `PLAY 1` does not do anything other than returning the load failure via AMCP and continuing with `existingclip`.

**Comment by ronag** [comment]
Yes, you are right, cannot reproduce the issue.
