### ISSUE TITLE
Incorrect upsampling of interlaced x:x:0 chroma.

### ISSUE THREAD

**Issue by CasparCGImport** [CasparCG/Server#41]
Converted from [SourceForge issue 3601847](http://sourceforge.net/support/tracker.php?aid=3601847), submitted by ronag

The GPU accelerated chroma upsampling of e.g. YUV420 is currently incorrect. We should probably let ffmpeg convert YUV420 to YUV422 and YUVA420 to YUVA422 before handing frames of to the caspar pipeline. See make_frame in util.cop.

e.g.

if(frame->pix_fmt == YUV420 && frame->interlaced)
   convert to YUV422

**Comment by walterav1984** [comment]
Duplicate ticket?
https://github.com/CasparCG/Server/issues/328
http://casparcg.com/forum/viewtopic.php?f=3&t=1631

Workaround:
Preconvert your 4:2:0 interlaced DV/Mpeg2/H264 footage in ffmpeg with the following parameter "-vf scale=interl=1" and choose a output videocodec that has 4:2:2 or higher chroma subsampling support for instance "prores" or raw "uyvy422". Two examples below:

"ffmpeg -i chromaerror.dv -vf scale=interl=1 -c:v prores chromafix422i.mov"
"ffmpeg -i chromaerror.dv -vf scale=interl=1 -vcodec rawvideo -pix_fmt uyvy422 -acodec copy -f avi chromafix422i.avi"

Native CasparCG Solution:
Since CasparCG ffmpeg producer can use ffmpeg parameters and or filters its possible to fix this in realtime with no hacks in CasparCG source code! Only tested file playback, streams IP/DV have not been tested yet! The following AMCP FILTER command fixes the chroma upsampling error:

play 1-1 chromaerrorfootage FILTER scale=interl=1,format=pix_fmts=uyvy422

Please update the CasparCG wiki "Chroma Subsampling" and "Producer > Filter" pages with these Workaround/Fixes for interlaced Chroma 4:2:0 based footage:

http://casparcg.com/wiki/Content_/_Media#Chroma_Subsampling
casparcg.com/wiki/CasparCG_Server#Producers_.28Input_Modules.29

Except from being GPU accelerated, and this FILTER preset can be added as a template to the CasparCG Client could this bug be closed?

**Comment by HellGore** [comment]
No, this should be fixed in CasparCG. No user intervention should be needed. And yes the bugs are duplicates.

Basically your workaround is exactly what would be done automatically in the server with the suggested solution by @ronag.

**Comment by ronag** [comment]
Fixed in 2.2.0
