### ISSUE TITLE
Feature Request: Make Initial media information retrieval optional/configurable

### ISSUE THREAD

**Issue by ajaymaru** [CasparCG/server#448]
We have a huge media library and every time Caspar CG is started, it takes anywhere between 15 to 40 minutes for this media information retrieval process to finish depending on activities on Caspar during that time (e.g., what is playing and how often). During this time, we are seeing an increased CPU usage which adversely affects the encoding process.

Please add a configuration that could disable or bypass the initial media information retrieval.

**Comment by ronag** [comment]
Would be great. I've had scenarios where caspar spams network storage to the point of unusability. Essentially DDoS.

**Comment by jesperstarkar** [comment]
What's the point of this listing, really? Other than logging?

**Comment by ajaymaru** [comment]
I believe it is a caching mechanism for CINF command. I may be wrong though.

**Comment by HellGore** [comment]
Yes, it was since the addition of the ffprobe for each video file in CINF/CLS. It was simply a way of letting each file be ffprobed only one time. CLS was too slow otherwise (and DDoS each time).

At first I had a media information retrieval implementation that persisted the metadata and kept it up to date using mtime comparison, but it was considered unnecessary. It was removed in this commit:

https://github.com/CasparCG/Server/commit/4abe37aece37ac56037f2c00cb3c4f1e2c2a9cee

`file_based_media_info_repository` the implementation was called.

**Comment by HellGore** [comment]
Each time a thumbnail was generated the csv file containing the metadata for every video file was rewritten with the new ffprobe result of the video file in question. It might be the only sensible way to do it, because I think it is too late to remove the duration/framerate information in CLS. The CasparCG client at least, depends on those columns.

**Comment by ronag** [comment]
@HellGore: It would be enough to change so that it is only allowed to e.g. process on file every seconds.

**Comment by jesperstarkar** [comment]
@ronag What will then happen in you do a CLS of a file not yet processed?

**Comment by HellGore** [comment]
But how should the CLS response look like in that intermediate time, while not all files has been probed? Block until ready or return N/A for those files not yet probed?

**Comment by HellGore** [comment]
@jesperstarkar you beat me to it

**Comment by jesperstarkar** [comment]
+1 for the persistent metadata/cache idea. Looks to me as the best solution

**Comment by ajaymaru** [comment]
The problem of getting CLS request for a file not yet processed is the same getting a CLS or CINF during the massive media retrieval process (on my setup it takes 40 minutes at times). Caspar CG may receive the CLS for a file before it gets to that file during the init. So, the issue will not really be "introduced" by making the media info retrieval optional or by throttling it.

**Comment by jesperstarkar** [comment]
The problem wit CINF on demand, as I understand (I might be wrong on this), is that the synchronous nature of the AMCP protocol means blocking during processing the CINF request. The overhead is the same in the initial retrieval process yes - but this runs asynchronously, hence not blocking processes as AMCP on demand will do (correct me if I'm wrong).

I think this set of issues need to be solved by a combination of:

1. Adopt the nature of the Thumbnail Generation for initial media data processing. Configurable and opt out.
2. Add back the proposed persistent metadata feature, to minimize the processing taking place.
3. Add proper handling of non-processed files for the CINF command. I'm not at my dev machine and can't tell what's currently happening if you try CINF on a file not yet processed, but I assume it throws an error?

**Comment by ronag** [comment]
@jesperstarkar The same thing would happen as when the media has not yet been processed.

Remember, throttling is the same scenario as the info not being ready yet (i.e. because it's processing 1000s of files). There should be no difference from the client side.

The CINF and CLS commands run on their own AMCP queue. The client will simply have to a a dedicated connection for these calls and simply wait.

**Comment by ronag** [comment]
Any client that connects to CasparCG should be aware that CINF can take time.

I'm fine with the caching of the replies. But the on demand scenario is EXACTLY the same as the media just being added to the server and the client calling CINF straight away... thus any client has to handle the problem anyway.

**Comment by ronag** [comment]
Another way would be to have CINF return a 'EAGAIN' error code to the client.

**Comment by ronag** [comment]
> But how should the CLS response look like in that intermediate time, while not all files has been probed? Block until ready or return N/A for those files not yet probed?

@HellGore: As above, the same thing should happen as if the media has just been added and the "automatic and optimised" media retrieval has not finished.

Again, adding throttling does not change the semantics of the API.

**Comment by ronag** [comment]
Moved to media_scanner
