### ISSUE TITLE
postion non-windowed screenconsumer

### ISSUE THREAD

**Issue by mauricev78** [CasparCG/server#487]
Hi all
I think it would be nice if we could position the screenconsumer
from the config file

i found line #219 en #220 in
/modules/screen/consumer/screen_consumer.cpp
are responsible for this

**Comment by Julusian** [comment]
After poking around with this area for #619, I have some ideas about how this should be achieved, but have some points that might be worth discussing before it is implemented:

### What should happen if both a device and x,y,w,h values are specified?
Currently, the x,y,w,h values are taken from the specified screen(device) with the width and height being taken from the channel if not running fullscreen.
My thinking is that this behaviour should continue but any specified values should override the existing calculations. Perhaps the aspect ratio of the channel should be preserved if only one of width/height are specified. I am unsure on this because it might be a bit unpredictable if the environment changes.

### How should this fit into AMCP commands?
It is possible to add a screen consumer over AMCP via ```ADD 1 SCREEN 2 FULLSCREEN```. It would be good to be able to specify the x,y,w,h values over AMCP also, so how should that be formatted? Something else to consider is that even with #620, the device selection does not apply, so that number (2 in the example) is ignored. Maybe the manual position should replace that? xrandr uses the format: 1920x1080+0+0 (WxH+X+Y), so perhaps the following should be accepted ```ADD 1 SCREEN "1920x1080+0+0" BORDERLESS``` Also, when these values are specified the fullscreen and borderless modes become very similar, it would be worth considering whether there is value in having both options.

Any input on the above is appreciated, this should be pretty quick to implement once decisions have been made on the above points.

**Comment by mauricev78** [comment]
I can only speak for my situation off course.
I normally try to work 1:1 in pixels.
So the channel should be runnend in its native resolution.
I all ready figured out how to make custom resolution channel and place it on its place by changing the earlier mentioned Lines. I find my self compiling the channels on a per job basis in the shop. Wich is fine but the position often needs to shift on site a pixel or 2 where this request came from.

For me X and Y are only important. But having the W and H  would be Nice.

What i understand is that there is a difference between Xserver and Windows. 
As far as i understand In Linux/Xserver the device number is a don't care as it handles screens laying on a big canvas wich is for the os one display and so it appears to CCG. I think in Windows X and Y should be in respect to the selected display. Linux will figure this out when Well documented

**Comment by Julusian** [comment]
I agree that most of the time 1:1 pixels will be done, but there are some occasions where I can see manual width and height being useful, maybe not skewing but just scaling the whole output up or down. They will be very simple to add so it may as well be done at the same time.

I found in #620 that windows treats the displays as one big canvas too, and the device number currently used is only to get the global coordinates of that display. If we call it an offset, rather than coordinates then the behavior you propose would make sense. It is still a little odd on linux, but it could be justified as the display selection already does not work, so will default to using the primary (or will it choose the leftmost?) and apply the offset from there.
If this approach is taken, then perhaps the amcp would be better served with x,y,w,h being seperate optional parameters added to the end of the command. This will make it be similar to the parameters for MIXER FILL, and the same order would work based on what I expect will be most used

**Comment by mauricev78** [comment]
i agree !

**Comment by ronag** [comment]
https://github.com/CasparCG/server/pull/1022
