### ISSUE TITLE
We should add live OSD diagnostics for developers

### ISSUE THREAD

**Issue by CasparCGImport** [CasparCG/server#56]
Converted from [SourceForge issue 3563170](http://sourceforge.net/support/tracker.php?aid=3563170), submitted by hellgore
- When developing flash templates it would be useful to get visual feedback in case the flash producer (or other producers) has late frames or is close to hitting a too high frame-time. This could be implemented as a simple producer overlaying visual warnings hooked in to the same mechanism as the graph/diag feature.
- Another producer showing errors from the log would be useful for developers for instant OSD feedback.

It would be advisable to introduce a command-line parameter to caspar or a configuration in the config-file called development-mode which would have to be set in order for any of these debug-producers to be available, as to not risk showing this kind of information in live-broadcasts.

**Comment by jesperstarkar** [comment]
2.1 introduces DIAG-straming over OSC, right? And I guess this can be closed.

**Comment by HellGore** [comment]
It is actually not the same, this is more like a producer on its own layer, showing diag-stuff above for example flash templates dropping frames etc. Like flashing the entire layer red, notifying the template developer visually

**Comment by jesperstarkar** [comment]
Well yes, that was (my) original idea.
But when it comes to flash producer, you get ALL the telemetry you need from Adobe Scout and the native telemetry libraries. Similarly will remote debug for Chrome give good profiling data.

So that covers profiling support for developers.

The next thing about this issue is the ability to log performance during production. That's where DIAG OSC and - perhaps we should revisit the idea of tracing dropped/late frames to the log? - comes in.

**Comment by HellGore** [comment]
> Well yes, that was (my) original idea

I was the one who wrote this feature request.

Anyway it would not only be useful for flash or html, but any event in the server causing a diag-tag.

Then again as you say OSC-diag is available now and makes it possible to do this kind of thing externally. Still we have the diag window built into the server, which also could be removed based on the same arguments, but I'm not sure.

Actually the diag-window could be converted to a producer so that it could be put out via any consumer, not requiring a local window on the server machine.

**Comment by jesperstarkar** [comment]
Sorry, I thought it was mine...

Diag producer would be nice. In combination with diag logging, which I think is the most critical part.
Diag logging + Log Socket would be the killer combination.

**Comment by HellGore** [comment]
I think a combination of scene producer and text producer could be used to print the last log statements (OSD style) as well, fading away lines shown for a certain while, which would also be nice as a separate producer.

Of course all of this would be possible externally as well.
