### ISSUE TITLE
Wrong response on TLS command

### ISSUE THREAD

**Issue by AleksandarAngeleski** [CasparCG/Server#588]
When i put multiple template files with same name and location but different types (flash, html, scene, psd), TLS command returns that all files is FLASH type.

Example:

test.ft
test.html
test.scene
test.psd

TLS response:

"TEST" 87332 20130202122350 flash
"TEST" 6627 20140207111736 flash
"TEST" 280762 20160615214129 flash
"TEST" 11097 20151222234132 flash

**Comment by HellGore** [comment]
This is not a bug actually, because it is up to the user to not have multiple files with the same name before the file extension. The reason that flash "wins" is that `.ft` is before the others when sorted alphabetically in the `std::map` in https://github.com/CasparCG/Server/blob/2.1.0/core/producer/cg_proxy.cpp#L88.
