### ISSUE TITLE
Make it build with latest VS Studio

### ISSUE THREAD

**Issue by ronag** [CasparCG/Server#646]

**Comment by seccpur** [comment]
Please make it compilable under VS2017

**Comment by krzyc** [comment]
I have just compiled 2.1.0 branch under VS2017 CE with no problems. Can you provide more details about your problems?

**Comment by seccpur** [comment]
@krzyc : Thanks for the feedback. Can you please tell which version of boost, CEF, SMFL, TBB, FFMPEG were used during your compilation on VS2017 ? I am planning to install these dependencies using vcpkg, hence the latest version of these libraries will be installed. Will this affect the compilation ?

**Comment by krzyc** [comment]
I have compiled "as is" - with included libraries.
Get source from GitHub, unpack large files in dependencies64, generate VS project, disable "treat warnings as errors" - and then compile.

Upgrading libraries may be hard, because of possible incompatibilities between versions. I saw that there are some efforts to upgrade CEF and FFMPEG at least - check out other issues and commits.

**Comment by seccpur** [comment]
Thanks I give a go and report back any anomaly.

**Comment by seccpur** [comment]
It compiles and builds like charm on VS 2017. Also VS 2017 can build the VS solution from cmakelists.txt without the need for installing CMake separately.
