### ISSUE TITLE
PSD Producer

### ISSUE THREAD

**Issue by ronag** [CasparCG/server#707]
Port from 2.1.0 to 2.2.0

**Comment by dimitry-ishenko** [comment]
If possible, I'd like to see the following things fixed in the PSD producer:
1. Text positioning is inaccurate. Text rendered by CCG is shifted up and to the left compared to the original (as viewed in PS CS5).
2. Font effects are not rendered. In my sample I've had stroke, shadow and satin -- neither one was rendered by CCG.
3. Animations are rendered as still image. I've imported a short .mov graphic into the timeline, but all I saw in CCG was a still image somewhere in the middle of the graphic.

**Comment by dimitry-ishenko** [comment]
Having toyed around with the HTML producer, it is my humble opinion that the PSD producer should probably be dropped altogether...

**Comment by dotarmin** [comment]
> @dimitry-ishenko Having toyed around with the HTML producer, it is my humble opinion that the PSD producer should probably be dropped altogether...

Could you explain why you think so? Do you feel it's unstable, have a lot of bugs, doesn't work as expected etc.

Thanks in advance!

**Comment by ronag** [comment]
@dotarmin I think he means that he can get the corresponding or better functionality through the html producer.

**Comment by premultiply** [comment]
The PSD (and scene) producer is one of the most important new features in CasparCG. It is perfect to create standard templates for daily operation without perfomance issues and packaged to a single file.
If we are talking about dropping something in the future then it should be the Flash producer...

**Comment by 5opr4ni** [comment]
Hi

The plan is not to drop these features, we just move them to the next release, we need to take a step back and make the core solid. 
I totally agree that the PSD are a huge thing and there are a large amount of people that now Photoshop and are potential template producers, and the PSD is dependent on the Sceneproducer. 

/Olle

**Comment by dotarmin** [comment]
> @ronag I think he means that he can get the corresponding or better functionality through the html producer.

I thought so as well but wanted just to check if we have missed something that we could catch. 

@premultiply As Olle wrote we do not have any plans of dropping the PSD and Scene producers. We just moved those out from 2.2.0 to focus on a stable and solid core. It will be back!

Best regards,
Armin

**Comment by dimitry-ishenko** [comment]
> > @ronag I think he means that he can get the corresponding or better functionality through the html producer.
>
> I thought so as well but wanted just to check if we have missed something that we could catch. :)

@dotarmin, @ronag is correct. As far as I can tell all of the functionality of the PSD producer can be implemented using the HTML producer.

If CCG supported rendering of layer effects, vector masks, etc. in the PSD producer and if the rendered image closely matched the original made in Photoshop, then I would agree with @premultiply. As it currently stands, PSD producer supports only a handful of features.

@premultiply if you don't mind me asking, what functionality of the PSD producer do you currently use?

I've made a small tutorial on how to get started with the HTML producer using Adobe Edge Animate:

https://casparcg.com/forum/viewtopic.php?f=5&t=4869

**Comment by premultiply** [comment]
Have you ever tried to do frame accurate playout from HTML templates?
As far as I know all these web authoring tools create HTML & JS output which is based on internal timers for drawing instead of waiting for the synchronous frame render calls from CasparCG.
Yes you could do it manually but I am not interested in writing complicated JS code by hand if there are tools like Photoshop which include a easy to use timeline feature and that create a single output file which will be nativly rendered by CasparCG and its internal features.
And yes there may be some features that are not supported yet but I am shure they will be supported one after one or get fixed if this feature is better known.

**Comment by Julusian** [comment]
I am closing this to clean up the number of stale issues. If someone wants to revive the scene producer, all of the closed tasks can be found at https://github.com/orgs/CasparCG/projects/1/views/1
