### ISSUE TITLE
Bluefish Producer

### ISSUE THREAD

**Issue by ronag** [CasparCG/server#715]
Port from 2.1.0 to 2.2.0

**Comment by ronag** [comment]
@jamesdwise if you make a PR I'm more than happy to re add this.

**Comment by jamesdwise** [comment]
I'm working on the Bluefish producer right now, and  I'm wondering if there would be any demand / interest for a config flag that allowed the producer to give caspar RGB frames instead of YUV.
ie. doing the colourspace conversion on bluefish device rather than in software.  
Also wondering if this might remove some of the colour space issues that the decklink has been seeing

**Comment by premultiply** [comment]
If the bluefish driver does proper color conversion on driver or hardware this may have a small benefit. But we have to check if bwdif is able to work in RGB mode first.

**Comment by ronag** [comment]
bwdif does have `AV_PIX_FMT_GBRP`, i.e. planar "RGB". If bluefish can give full range RGB that would be faster. We just need to make sure that bwdif correctly resolves to `AV_PIX_FMT_GBRP`.

**Comment by Julusian** [comment]
Can this be closed? #951
