### ISSUE TITLE
More nugetifying

### ISSUE THREAD

**Issue by ronag** [CasparCG/server#734]
Nuget:

- [x] CEF
- [ ] FreeImage
- [ ] TBB
- [ ] OpenAL
- [ ] SFML headers?
- [x] CEF headers?

???:

- [ ] zlib
- [ ] liberation-fonts
- [ ] roboto-fonts

**Comment by Julusian** [comment]
@ronag what are your thoughts on the casparcg org maintaining its own nuget packages for the remaining dependencies or ones which are too outdated on nuget?
It should only add work now for initial setup and when we want to update something, and means we can move all windows deps out of tree

**Comment by ronag** [comment]
I've fixed CEF

**Comment by ronag** [comment]
Maintaining our own nuget sounds like a good idea as long as some actually maintains it. @Julusian

**Comment by Julusian** [comment]
I have recently discovered https://github.com/Microsoft/vcpkg
It looks to be more suitable than nuget for c++ dependencies. 

It will integrate with CMake better and has almost every dependency we use on it, the one exception being CEF.
I think it is worth looking into instead of nuget for windows dependencies. It could be used on linux too, but I prefer using system libs there.

**Comment by Julusian** [comment]
This is replaced by #1502, which removes the use of nuget and instead downloads and unpacks prebuilt or source packages over http using standard cmake functionality.
