### ISSUE TITLE
apt-lists size

### ISSUE THREAD

**Issue by ronag** [CasparCG/server#748]
Is there a way to avoid having apt-lists in the repo or possibly reducing its size? Almost 40MB.

**Comment by ronag** [comment]
I suggest we create a docker base image with the apt-list and then derive from that so we don't need to have this in the repo. Is there no ubuntu docker image with reasonable up to date apt-list which are good enough?

**Comment by Julusian** [comment]
@k0d why do we need to cache these? I was assuming it was so that the build would be consistent, but at runtime it will have the latest versions so is that a benefit?
What about if we have a separate repo which is for the docker image? That could push to dockerhub(or similar) and then the builds in this repo can pull that image? This would also mean we wouldn't need to compile boost or ffmpeg as often, which would help with build times.
