### ISSUE TITLE
"No connection could be made" with Client

### ISSUE THREAD

**Issue by Znarkus** [CasparCG/server#956]
### Current Behaviour
When I start latest next Client (`CasparCG Client 3dad82ffaf7b097b40d91095c87ca0f4e7c367ee.zip`) with latest server (`casparcg-server-62ceef88a362be179c3576bba9621868ee8ba56e-windows.zip`) it fails with these errors in the server log output (see attached log).

Is there anything more than the server, that  I need to start?

Please let me know if there's anything more I can provide or help with!

### Attachments
[caspar_2018-04-01.log](https://github.com/CasparCG/server/files/1866499/caspar_2018-04-01.log)

**Comment by dotarmin** [comment]
I have tried this and I can reproduce the error when `scanner.exe` is not started. But server **does not fail** or anything, it still works. This is more a client related bug because the client tries to fetch thumbnails even if `scanner.exe` is not running.

> @Znarkus Is there anything more than the server, that I need to start?
If you use the `casparcg_auto_restart.bat` script it should start what you need or you could simply start `scanner.exe` first (bundled) and then `casparcg.exe`

/Armin

**Comment by Znarkus** [comment]
Okay thanks! Submitted a PR to update the readme to reflect this :)

**Comment by dotarmin** [comment]
> Okay thanks! Submitted a PR to update the readme to reflect this :)

Thanks! I think it has been merged already! 👍
