### ISSUE TITLE
PAL HTML FONT APPEARANCE

### ISSUE THREAD

**Issue by PeterAkakpo** [CasparCG/server#967]
### Expected Behaviour

Font should me clear and smooth on all channel modes

### Current Behaviour

font is not clear and smooth on PAL mode, but clear and smooth on 1080p2500

I HAVE ENABLED **CLEAR FONT TYPE**  AND **SMOOTH EDGES OF SCREEN FONTS** ON WINDOWS 

### Steps to Reproduce 
change channel mode to PAL either in config or with SET 1 MODE PAL and the run the html template that has text on it.
### Environment
* CasparCG Server version: 2.2.0.4
* Operating system: Windows 10

### Attachments
PAL MODE
![pal](https://user-images.githubusercontent.com/7926382/38914525-451118e0-42cf-11e8-8dda-fdc0608274a9.png)
 
1080P
![1080p](https://user-images.githubusercontent.com/7926382/38914790-79aa0c50-42d0-11e8-822b-9dfe630e6619.png)

**Comment by jesperstarkar** [comment]
Do you use decklinks? Can you compare this with running the CasparCG channel in HD and have the decklink card downscale to SD?

**Comment by PeterAkakpo** [comment]
@jesperstarkar can you direct me on how to "downscale decklinke to SD from HD. I have used the Desktop Video Setup and under the converter section, i have HD to SD set, but, my output is still HD (1080p2500)

**Comment by jesperstarkar** [comment]
If that doesn't work, I don't have any clues. Sorry about that.

**Comment by Julusian** [comment]
How are you grabbing that frame?
To me, the issue with the PAL one looks like deinterlacing artifacts. What does 1080i5000 look like?

**Comment by baltedewit** [comment]
> To me, the issue with the PAL one looks like deinterlacing artifacts.

I agree, used to have things like this happen with vertical scrolling text as well. Try making the font a bit bigger. Basically, the lines in PAL take up so much of your text that it will start to look ragged. It also helps to not have any thin lines in the text like serifs, but I guess you already have a bold font.

Oh, and the screen consumer is a bad bet on checking this. The deinterlacer is not of very high quality. It should suffice to make a recording and play it back or use a decklink output with a high quality monitor.

**Comment by dotarmin** [comment]
> @Julusian To me, the issue with the PAL one looks like deinterlacing artifacts. What does 1080i5000 look like?

@PeterAkakpo, could you please check this and reply to Julian? 😄

**Comment by PeterAkakpo** [comment]
this is the result of 1080i5000. It is much better than setting the channel mode to PAL
![1080i500](https://user-images.githubusercontent.com/7926382/39048254-b42d485e-4494-11e8-8674-fc0322efbb23.png)

**Comment by Julusian** [comment]
@PeterAkakpo The effect is still there in that frame of 1080i50, and only on the second line which looks to be the only one that is moving. Its not as bad as your PAL sample because the text is much bigger. To make it a fair test the text would need to be the same pixel size. 
I don't think there is anything we can do to fix this, the issue lies in how interlaced video works.

I had this problem myself a few months back, but I didn't have time to look into a proper solution.
Some things you could try are to slow the text down or to make it larger. Both of these should help minimise the effect. Or maybe a different deinterlacing algorithm would work better for you, if you can control that.

This was my case in 2.1, on a 1080i50 channel and the issue is clearly visible with the scrolling text vs the non-moving clock, coming from the same html template
![27781916_10156257402012384_1550066641_n](https://user-images.githubusercontent.com/1327476/39088652-e38fe13c-45ad-11e8-97c9-3b19789fca53.png)

>Oh, and the screen consumer is a bad bet on checking this. The deinterlacer is not of very high quality.

@baltedewit in 2.2 the channels always run in progressive with consumers interlacing as needed, so the screen consumer doesn't deinterlace.
